export enum Activity {
  DEVELOPMENT = 'DEVELOPMENT',
  QA = 'QA',
  SUPPORT = 'SUPPORT',
  MEETING = 'MEETING',
  DOCUMENTATION = 'DOCUMENTATION',
  TRAINING = 'TRAINING',
  OTHER = 'OTHER',
  ADMINISTRATION = 'ADMINISTRATION',
  RESEARCH = 'RESEARCH',
}
